name: Deploy My Project

on:
  push:
    branches: ["master"]

# 1. 동시성 제어 (필요시 추가)
concurrency:
  group: "pages"
  cancel-in-progress: false

# 2. GitHub Pages 배포 권한 설정 (필수!)
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: jsbzzz/action-deploy@main